[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
token_airdrop = "9yk1CYdhn5mLFj6Wzz8rLjJ92HyTowMqELLQmB8YAgSr"

[programs.devnet]
token_airdrop = "9yk1CYdhn5mLFj6Wzz8rLjJ92HyTowMqELLQmB8YAgSr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/ledgerninja/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
